### ISSUE TITLE
Possible workarounds for iOS?

### ISSUE THREAD

**Issue by jacobshiff** [yahoo/gifshot#62]
Hi, Would love to use this AMAZING library, esp. the webcam feature, for Safari + Android on iOS. Are there any possible workarounds so it can work in those browsers as well?
Thanks!
Jacob

**Comment by gfranko** [comment]
Looks like the latest iOS version supports the `getUserMedia` API, so Gifshot will work!

**Comment by tetreault** [comment]
@gfranko @jacobshiff 

on iOS it returns the following error: 

```
Unhandled Promise Rejection: NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

You guys have any luck in iOS (in particular iOS 11)

**Comment by tetreault** [comment]
I was tired and not paying attention yesterday and it was my own stupid mistake! Running GIFShot on page load was great for my browser tests but obviously was failing on mobile because it requires that explicit gesture to run the library since its running video.play under the hood. Now that I put gifshot inside a click handler its fine on mobile. Having an issue with webviews but i'm sure i'll figure it out.
